# Generated by Django 2.2.13 on 2020-06-20 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200620_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='currentStory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='current_story', to='blog.Story'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='parent_story', to='blog.Story'),
            preserve_default=False,
        ),
    ]
