# Generated by Django 2.2.13 on 2020-08-04 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_joinstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
