# Generated by Django 2.2.13 on 2020-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_story_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinstory',
            name='story',
        ),
        migrations.AlterField(
            model_name='story',
            name='members',
            field=models.ManyToManyField(related_name='members', to='blog.JoinStory'),
        ),
    ]
