# Generated by Django 2.2.13 on 2020-08-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200804_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='members',
            field=models.ManyToManyField(related_name='members', to='blog.JoinStory'),
        ),
    ]
